language: java
sudo: false
jdk:
- oraclejdk11
addons:
  apt:
    packages:
    - graphviz
before_install:
-
after_success:
- "./.travis-deploy-artifacts.sh"
cache:
  directories:
  - "$HOME/.gradle"
  - "$HOME/.m2"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/c489689605a7c1ec7cb6
    on_success: change
    on_failure: always
    on_start: never
env:
  global:
  # SIGNING_KEY
  - secure: 0D2TaH21OB4LV4590KuL0Wu5GcLMH2EaFCUfhwET7vEV/4xeGIwd0BfM5a3tIZvJj1H1jJFpRvnunKwVoy+RiOTnc9wa0K2bsne+GqoaHmBhbvzkgdsfBw0W2f5S0zbL4gACgQ7d6IQjFNlAoZl1QQYlMI7CPTqffIoe/izokiIBDqJUnKc5UP+DoAiL6zeynk6SqyORVvBZ1N/qc+w3A+B/MDzjbNT1d10J4QeIz73a3bf/uI5qNzoUvZNXXw4ByRXHk6JblR9sMCi/2eygro06nsaalesaHyvpuGCwRTpBuE+Kq+n/qcWF3fZnNIL2ZkpTwphJX22kaRlAYesi2g1D89Apx1i12xAruBXZaQWWEKKHBknGLseVuibjlYDgNiYM5Tcp3psDZpCTpapyEksNf8G/lu72LPAnPsOU0OoSSYlOU30hA7WRQIhnQjI0qfeuKgVDTvzolbxeFJi2Np38ociZfkYkD9Zhub4FFKOsnBp2AaphYTUfdn52GQ/K9YXXhd42q8DCzy+qBe4Pf+2bXTRer7DuQ63iCB/JysGwdR2u7tV8iSpw+WLA7xX+AWpFbk/V7aupNoz+TI5Qx3rzqCNqUNXdXWMPgBSYql1rgZxxv9kp87ZoiziSHG4doBP09BDTpXkIHv6LkxAEvJZ0n9M4c3aXKHnmyLMlTy4=
  # SIGNING_PASSWORD
  - secure: HYoW4VKGcoHDP+2WKT3pxP55QNrZrKkdhXmanGhnMb7Q7xuHw7jUdNR/56/RbLRL2kmFaEhTgHYsSGYn7kZIBKidtSKCKfWJkUrg3hxtNTWpbwwBJEOGQZGnixRFnhH1YuH7ZbF1KY1AHwuNfAUYemwjL0/3DjqhFIHl2QwPI86fBCv8cYWdLv3KmSQjsCK3bM36VTmX3xQXC3RH+XAC+Xxpvpurarh7DN3vr5+Szw0X7M0vsVLt/wiluD3llZwx2m+yWl1jBbu/yuqfw7mN7pIpAwvvtxySUesnZVXzzdCeOKPRHJWZkzRczIwbxPt6tTCjE8VLERIO0OI+oJzYseFzISc01UxsOBEJIwRJi053rjdaE86F/I17O7yjzG4aiFusNiaPuQbEha8WP+ooiq1VazR1MXVDz9k2g36V/h76EnbfL/8r9SsycFsygzXpSH3Un9aleh6doADDMLh3Xi3dLZ5K5h3KwrqEXWeU++ekhPuxjxCqtBV4uhbmK+VLREp0MaBtvoRccO+jd79YyvYrQpa+aXHlunV1WQD7n0datWgjd3j3z6J/CLlUBzqKqxbPiJWni0s3IuO7Ls3Q8k3JT0xmlzUXyCEqmVOL2pmkcA1T4DHpHz9xGrVkPiijZIW59HieS823AyAoRSS17Xn46eMaUy9qEcC0wQTn0ac=
  # SONATYPE_OSSRH_USERNAME
  - secure: Y2SD/6zcnaFRRQ824pthUe0+HSOrlyh07Ms4tgc9kb8E5ulNlO1DakgVilr5Q4dnjUs8WGp+uFfLeAvLn+26t7yAHFcYWHHrBJzCGwLJVaw1bfxkduIf8r9Z5RzBXOQTEzMY63GbamympnszHebmfSaxsYT1wibJbAXOEHcNy4pUZCgTtTZz5f4aKSqZpJr2NqirQgIitn9KbLHtB2+K6TFAg8TWnr1wrxym12iUftI3CkPKlCshLwKAnh1er9gtImPD3Q7cIBB6fYNy+4EV8leZqcNCBCG03xc+MJohRhx6dhQCV5FQV9Megcz2s6veOwPkO4/zfq96lzXaeDZoXaVfZZJ5ntx10wGjwZzjAFdzb+7OImLu86q6+X2gwtlLHA53bM0lNh5ElBEo1OUZwy19/xC/p2OiOm/BCnxXOWwTg4s5vz8CN489WGQawQDP2TkyRquHzYwvbQA66jeMUHmurz5l+S7BDB7iYqehlTpEqDarlbv1Q7Exnng0idMmHrD5mnJbcG8G/S5vDyEnlpKVPTtaBpdFd/oGBZNjjrMVqRPctxUZppQ4ym5JWtDUIxJl0DJqRgrSSGEI5Y6paRpjn69ygBO3VwRdp81DYsulUL+kFEMM9+Y6xt2EcETwsaXds0wBg3l8BdL26/4RT/z+OGc40hJjckYMNQykbQo=
  # SONATYPE_OSSRH_PASSWORD
  - secure: szghhbDZP4YhCsC/Q6pNp+fLM3UgnJ8Bkl3lZ6MBAeIVciRQ2LhW967YP+xbvF5tHKn45veFxlqCxVwd3UKSWIxI70qzBaWLRVEfMtvZVMYzLwJzf+AsXPnO1RnNlDS4FIz+up3276mmjy6z4QDT8pPfJEuYtMM/pPmKxPnWT6X9B4V3Dg1+TJDgnLovwjoZnS6PzWhsMLDKeS3GZMuav8I3Cn9DOYJwbdYVe00fuiXvwgfeW/R0sKZntlVXqn5Hc/SRddYKXj8xM86Ub4fOqAakb9gcRw5cRnUj2S4oYRww4Vo4Q8j7KBvbBbJDCAbSRTVJPyE9n52sk/sm02VN8d5LQ9+FrPQ7mJzNFxLR2ulq93ulAiHRAf9WqAVmslDOYN/NMdOjSR2Rr3TQbI9wplxSyeOV8ckkIhOj3Wbvi2BE+fpO2LlOKVOW8y+PA0uhxkOht3bRBy6mFlF7Mws9OUx0gY0ilX8NPn6xA2jyWbp/Kbj5nxVkO7Bw6hfmJNk74xl4kfdsMaHDr2YSSCTdBu2QJ0sm18HsLcI7SuEkSeKUmwS76pq2fc3+y90n/R/DQHVGlaSbEdBuGsdGZ5w5QdGMwbd+5rEgqj3Px1Qjht6QdYF0ltwXO2sALL+8KHzcEIB3zFmsseJL2uSIXk7V1Q73/UyMkIrsOYq8QWGm4vU=
  # GH_TOKEN
  - secure: jXV/hJQ90pqSEq5lo75x6l+fiSbrcG732TQ1K3u1YT2YQCzVmEi5yw6AcH3U+XRdMV1mqTl83usgTMCvF6+xN9GjA+C0/aXvA2egcH9vCdIVzDFO+BY9QbDq6Y9OczHvlN25fl3BhMOQy7Xi0IMezs6MXwA+iFadi/sgh0QKLxjJlST4KpNQNv6aUsaLXSG5cfPRZzLN8bCU3x6rkCIf6jrSZLWKIcOwTGubmVqNBxmlSZYQpzf7KpqJld/9e8Z7DR5HrsVm9HRjGnnUNmlPIibhE9OOu5czQFPoK3XVl9QDbVX1MA2egcq+nyDAwDE5EdT2jfJhDuQaw77wEvactmXck8ZM0gQ6yecaF/WRcwt7Wh/PNQ+vF17Xy06pI61rKEmOIFcDDYZ3aS/XhDhamix5RYXQIZuICvFGHDGi4U9F5pmZPFvP8k+cTCAk7ME8nGYEyeMXNfUUTJVRg516ONff7lSf1pySARtPIOZPNy61Lo7yCkoqmN2Mp3IrvnWqLakJQKlBLWFjjwiHI5wMiKVxICAGf/aBYnKn8tJKW1VRovw5ld0BlAXswdcJjGjyLVWSIm4iD/ijPjNGLq/UFVklUfOLr17WahAPNt7Tk8tuMXD9KoIfSY4uX3uTtezR6xH8sbdQNjnBDzXXKB9iFaksM1vTEJ2kZ4uXikr4TNE=
