spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    serialization:
      indent-output: false
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: false
logging:
  file: log/hawaii.log
  level:
    org.hawaiiframework: INFO
    org.springframework: INFO
hawaii:
  time:
    enabled: true
    timezone: UTC
  async:
    configuration: ./config/async-config.yml
  logging:
    filters:
      kibana-log:
        enabled: true
        order: -108
        http-header: X-Hawaii-Frontend-IP-Address
      kibana-log-cleanup:
        enabled: true
        order: -110
      request-duration:
        enabled: true
        order: -109
      request-id:
        enabled: true
        order: -106
        http-header: X-Hawaii-Request-Id
      request-response:
        enabled: true
        order: -105
        fallback-to-file: true
        directory: /tmp
        max-log-size: 50k
        # For console logging, the allowed content types, empty means allow all.
        allowed-content-types:
        - application/json
        - text/plain
        - text/xml
        - application/vnd.spring-boot.actuator.v1+json
      transaction-id:
        enabled: true
        order: -107
        http-header: X-Hawaii-Tx-Id
      user-details:
        enabled: true
        order: 110

---

spring:
  profiles: dev
  jackson:
    serialization.indent-output: true
logging:
  level:
    org.hawaiiframework: DEBUG
